- .copier-answers.yml
Automated changed by Copier.yml workflow
Rejected changes (if any):
```diff
diff a/README.md b/README.md	(rejected hunks)
@@ -1,25 +1,171 @@
-# COPIERTemplate
+<p>
+  <img width="150" align="right" src="docs/src/assets/logo.png">
+</p>
+
+# COPIERTemplate.jl - Copier OPInionated Evolving Reusable Template
-
[![Stable Documentation](https://img.shields.io/badge/docs-stable-blue.svg)](https://abelsiqueira.github.io/COPIERTemplate.jl/stable)
[![In development documentation](https://img.shields.io/badge/docs-dev-blue.svg)](https://abelsiqueira.github.io/COPIERTemplate.jl/dev)
+
+[![Lint workflow Status](https://github.com/abelsiqueira/COPIERTemplate.jl/actions/workflows/Lint.yml/badge.svg?branch=main)](https://github.com/abelsiqueira/COPIERTemplate.jl/actions/workflows/Lint.yml?query=branch%3A …
```
> [AUTO] COPIERTemplate.jl update

- CHANGELOG.md
- copier.yml
- template/.JuliaFormatter.toml.jinja
- template/.editorconfig.jinja
- template/.markdownlint.json.jinja
- template/.pre-commit-config.yaml.jinja
- template/.yamllint.yml
- template/.yamllint.yml.jinja
- test/runtests.jl
Option Indentation now available to set the indentation length of the many linters and formatters.
✅ Closes: #44
> feat: 🎸 Add option for Indentation length

- docs/src/developer.md
Inform how to run copier with a dirty state.
> docs: ✏️ Add tips on testing to developer docs

- CHANGELOG.md
- copier.yml
- test/runtests.jl
AskAdvancedQuestions creates a separation between the basic questions
and the questions that are opinative or advanced. In the future, we can
create more fine-tuned defaults and let the user choose from them.
✅ Closes: #67
> feat: 🎸 Add AskAdvancedQuestions to allow stopping early

- .github/ISSUE_TEMPLATE/10-bug-report.yml
- .github/ISSUE_TEMPLATE/20-feature-request.yml
- .github/ISSUE_TEMPLATE/30-usage.yml
- .github/ISSUE_TEMPLATE/99-general.yml
- .github/ISSUE_TEMPLATE/config.yml
- template/.github/ISSUE_TEMPLATE/10-bug-report.yml.jinja
- template/.github/ISSUE_TEMPLATE/20-feature-request.yml.jinja
- template/.github/ISSUE_TEMPLATE/30-usage.yml.jinja
- template/.github/ISSUE_TEMPLATE/99-general.yml.jinja
Fix title in the bug report. Fix links in the checklist.
✅ Closes: #76
> fix: 🐛 Fixes to the issue and PR templates

- docs/src/10-full-guide.md
- template/docs/make.jl.jinja
> docs: ✏️ Improve documentation for new packages

- copier.yml
- docs/make.jl
- template/docs/Project.toml.jinja
- template/docs/make.jl.jinja
- template/docs/src/90-developer.md.jinja
According to more recent documentation, prettyurls should be set to true
and LiveServer.jl should be used.
✅ Closes: #54
> docs: ✏️ Change prettyurls and use LiveServer for docs

- .github/workflows/Test.yml
- src/COPIERTemplate.jl
- template/.github/workflows/Test.yml.jinja
- test/runtests.jl
A previous commit included the key continue-on-error that should inside
the raw enclosure. Tests did not run because of #119.
✅ Closes: #120
> fix: 🐛 Run tests correctly and fix bad raw enclosing

- copier.yml
Prints a message:
```bash
Your project YourPackage.jl has been created successfully! 🎉
Next steps: Create git repository and push to Github.
$ cd YourPackage.jl
$ git init
$ git add .
$ pre-commit run -a # Try to fix possible pre-commit issues (failures are expected)
$ git add .
$ git commit -m "First commit"
$ pre-commit install # Future commits can't be directly to main unless you use -n
Create a repo on GitHub and push your code to it.
Read the full guide: https://abelsiqueira.com/COPIERTemplate.jl/stable/10-full-guide
```
using [copier feature `message_after_copy`](https://copier.readthedocs.io/en/stable/configuring/#message_after_copy).
We consider that this message is printed after generating a **new package** with COPIERTemplate.jl. The message in the case where a user use …
> Print post-installation info

- docs/src/90-developer.md
- template/docs/src/90-developer.md.jinja
Instead of using orgremote for the organization git, use upstream.
Explain what to do if you have writing rights and don't need to fork.
Explain why we have two remotes.
✅ Closes: #165
> docs: ✏️ Change orgremote to upstream and clarify instructions

- CHANGELOG.md
- src/COPIERTemplate.jl
- test/runtests.jl
Instead of using the copier.yml from ~/.julia/** use GH url.
TODO
Fixes #146
> Allow optional src_path argument to generate that default to URL

- .github/workflows/ReusableTest.yml
- .github/workflows/Test.yml
- .github/workflows/TestOnPRs.yml
- CHANGELOG.md
- copier.yml
- docs/src/20-explanation.md
- template/.github/workflows/ReusableTest.yml
- template/.github/workflows/Test.yml.jinja
- template/.github/workflows/{% if SimplifiedPRTest %}TestOnPRs.yml{% endif %}.jinja
- test/runtests.jl
Using the workflow matrix and conditions to include and exclude, we only
run the full matrix on pushes. For PRs, only 1 build is made, using
ubuntu and Julia 1.
Also adds a question TestPRsOnlyOneMachine to include the same in the template. Defaults to true.
✅ Closes: #105
> feat: 🎸 Only run ubuntu with Julia 1 on PRs

- CHANGELOG.md
- src/COPIERTemplate.jl
The generate_missing_uuid argument is not necessary anymore since Jinja
generates one for us.
BREAKING CHANGE: 🧨 The API of generate has been changed.
✅ Closes: #189
> refactor: 💡 Remove generate_missing_uuid argument

- test/runtests.jl
Make the folder difference in the test more robust by usign regex to check for \.git\ or /.git/ or .git/. This also makes sure that the .github folder is not skipped.
Closes nothing.
> Fix tests on windows

- CHANGELOG.md
- Project.toml
- src/COPIERTemplate.jl
- test/Project.toml
- test/runtests.jl
If dsp_path/Project.toml exists, read from it to guess some of the
answers. Passing data to the generate function will override the guessed
values.
BREAKING CHANGE: 🧨 Applying to existing packages has a different behaviour now.
✅ Closes: #116
> feat: 🎸 Read from dst_path/Project.toml to guess answers

- CHANGELOG.md
- src/COPIERTemplate.jl
- test/runtests.jl
If possible, determine the package name from the destination path.
BREAKING CHANGE: 🧨 PackageName is now automatically defined, instead of asked.
✅ Closes: #151
> feat: 🎸 Determine package name from the dst_path

- .github/workflows/Test.yml
In the ${{ ... }} commands, only single quotes are allowed.
> fix: 🐛 Cannot use double quotes in interpolation in GHA

- .github/workflows/Lint.yml
- .markdown-link-config.json
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- docs/make.jl
- docs/src/20-explanation.md
- docs/src/index.md
- lychee.toml
- template/.github/workflows/Lint.yml
- template/.markdown-link-config.json
- template/.pre-commit-config.yaml.jinja
- template/README.md.jinja
- template/docs/make.jl.jinja
- template/docs/src/index.md.jinja
- template/lychee.toml.jinja
Instead of running a pre-commit hook for the link-checker, run lychee on
the Lint.yml workflow. Also set the docs linkcheck to false.
✅ Closes: #160
> feat: 🎸 Use lychee instead of markdown-link-checker

- CHANGELOG.md
- copier.yml
- test/runtests.jl
If AnswerStrategy is recommended, then we use our default. If it is
minimum, then we answer no to everything. Otherwise, we ask as usual.
✅ Closes: #235
> feat: 🎸 Add AnswerStrategy to allow minimum additions

- docs/src/10-full-guide.md
- src/COPIERTemplate.jl
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/10-bug-report.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/20-feature-request.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/30-usage.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/99-general.yml.jinja
- template/README.md.jinja
- template/docs/src/90-contributing.md.jinja
- template/docs/src/90-reference.md.jinja
- template/docs/src/index.md.jinja
- test/runtests.jl
Create a update wrapper calling the internal Copier update. The
overwrite=true argument needs to be passed to mimic the CLI behaviour.
Updates the guide with specific information to update.
✅ Closes: https://github.com/abelsiqueira/COPIERTemplate.jl/issues/113
> Create update wrapper and add update info to guide

- src/COPIERTemplate.jl
- test/runtests.jl
If generate is run in a path that has an answer file, a warning message
is shown to remind the user of the update command.
✅ Closes: #247
> feat: 🎸 Create safeguard when running generate in existing pkg

- .github/workflows/TestOnPRs.yml
- copier.yml
Although we don't like the overwriting, for first application
in existing projects it is necessary.
Closes #257
> Don't skip README.md and docs/src/index.md

- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/10-bug-report.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/20-feature-request.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/30-usage.yml.jinja
- template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/99-general.yml.jinja
- template/.github/{% if AddGitHubTemplates %}PULL_REQUEST_TEMPLATE.md{% endif %}.jinja
Based on comments made on https://github.com/JuliaSmoothOptimizers/JSOSuite.jl/pull/163 by @tmigot.
> Updates based on feedback from @tmigot

- Project.toml
Julia registry has this package with the lowercase UUID. Since TagBot checks the UUID of the package
against the registry, it doesn't find it.
Closes #294
Closes #294
> Use lowercase on UUID because of TagBot

- .github/scripts/check-docs.bash
- .github/workflows/TestGeneratedPkg.yml
GH runs custom steps as `bash -e` (`errexit`), which means any command
failure leads to the shell terminating.  To simplify this complexity,
factor out to a dedicated script, which we can now also check with
shellcheck.
[TestGeneratedPkgs on my fork](https://github.com/suvayu/COPIERTemplate.jl/actions/runs/9799231708) :white_check_mark:
Note: `shellcheck` says the last line could be `if ! cmd`, but for this script that would be rather cumbersome, so I ignored it. ([SC2181](https://www.shellcheck.net/wiki/SC2181))
Closes #322
> workflows: fix doc generation check

- CHANGELOG.md
- Project.toml
- README.md
- copier.yml
- docs/src/10-full-guide.md
- docs/src/index.md
- src/BestieTemplate.jl
- test/runtests.jl
BestieTemplate.generate only works for new folders now.
BestieTemplate.apply was created to handle existing folders.
Closes #301
Breaking change: generate stops working for existing packages and apply should be used instead.
> Create apply function and change generate

- Project.toml
- src/BestieTemplate.jl
> Add a preamble to the question with the link to the docs

- docs/src/10-full-guide.md
This makes the pre-commit installation happen before Julia is opened, so
users don't have to open a second terminal, or close and reopen Julia.
Closes #303
> Move the pre-commit installation a bit earlier in the docs

- docs/make.jl
- template/docs/make.jl.jinja
Remove some options that are set for default values.
Remove nice_name and let Documenter use the title of the page.
Remove link_check=false to make Documenter run the link checker.
Closes #357
> Clean up docs

- CHANGELOG.md
- copier.yml
- test/Project.toml
- test/runtests.jl
Uses regex to make sure that the package name starts with a capital letter and contains only letters and numbers.
Closes #373
> Validate PackageName

- src/BestieTemplate.jl
Even if the dst_path contains a .copier-answers.yml file,
guess the starting answers. This only happens if the user
explicitly uses warn_existing_pkg=false, so it is in line
with the expectations.
Closes #383
> Guess on apply for pkg already using copier

- CHANGELOG.md
- src/api.jl
- test/runtests.jl
The quiet argument is used by copier to define its verbosity.
This adds the quiet keyword argument to the wrapper functions
to decide whether to print/log.
quiet is added to the tests in places that did not have it yet.
Closes #379
> Use keyword argument quiet to define verbosity of wrapper

- .github/workflows/TestGeneratedPkg.yml
Run pre-commit run -a twice in the generated package.
The first run should fix all issues.
The second run should pass because all issues were fixed.
This ensures that the promoted experience in package generation
is correct.
Closes https://github.com/abelsiqueira/BestieTemplate.jl/issues/390
> Test pre-commit in the generated package

- src/Copier.jl
There was type piracy of `Base.copy`,
because it was overloaded without any of the types belonging to this package.
This can cause spooky action at a distance -- just loading this package changes what `Base.copy` does even if you don't load the module directly.
To be precise it turned what used to be a error into an unexpected behavior. This is misdemeanor type piracy. This is thus very unlikely to have actually caused anyone problems.
But still it is poor code form.
Fortunately the code has already been written to refer to `Copier.copy` in the place it is used.
Which in this case previously resolved to `Base.copy` which was imported by default (check `@which Copier.copy`). And the `Copier` module doesn't use `Base.copy` already, so we can just rmove the `Base.` and it will shadow the …
> Remove type piracy of Base.copy

- .github/workflows/ReusableTest.yml
- CHANGELOG.md
- copier.yml
- src/debug/Data.jl
- template/docs/make.jl.jinja
- template/test/runtests.jl.jinja
- test/Project.toml
- test/test-consistency-with-copier-cli.jl
- test/utils.jl
This is the default in the Julia ecosystem, both in the official guidelines and on various styles.
The Julia files in the template have been changed to use 4 spaces.
The other files in the template are still using 2 spaces.
This should be changed to 4 when pre-commit is run for the first time.
Update the consistency tests that verifies Copier's API to run the
pre-commit before the comparison, to ensure that formatting changes
don't influence the tests.
Closes #403
> Change the default indentation from 2 to 4

- CHANGELOG.md
- copier.yml
- src/debug/Data.jl
- template/.github/workflows/Test.yml.jinja
- test/test-bad-usage-and-errors.jl
- test/utils.jl
Creates a constant `JULIA_LTS_VERSION` for internal use.
Changes the deafult of `JuliaMinVersion` to use the constant.
Create `JuliaMinCIVersion`. It defaults to `lts` if `JuliaMinVersion` is equal to `JULIA_LTS_VERSION`. Otherwise, if defaults to `JuliaMinVersion`.
Closes #400
> New question: JuliaMinCIVersion

- template/.github/workflows/Docs.yml.jinja
This is recommended in the Documenter.jl documentation (v1.7.0).
Although not everyone uses Plots and GR, this should not raise
issues.
Closes #132
> Add GKSwstype in the docs workflow to prevent GR warnings

- CHANGELOG.md
- copier.yml
- copier/code-quality.yml
- src/debug/Data.jl
- template/test/runtests.jl.jinja
- template/test/{% if AutoIncludeTests %}test-basic-test.jl{% endif %}.jinja
- test/runtests.jl
If selected, AutoIncludeTests will add a snippet in runtests.jl that
reads through all test-*.jl files and include them inside a @testset.
Because of this, test/runtests.jl is not ignored anymore.
Closes #261
> New question: AutoIncludeTests

- src/BestieTemplate.jl
I create new packages rarely enough that I generally don't remeber by heart what command to run. I had the same issue with PkgTemplates.jl and one thing I really liked is that I could do `?PkgTemplate` in the REPL and it would kindly remind me how to use it (to be fair, that was just dumping the Pkg README in the terminal, hence I had to do a bit of scrolling).
This PR adds the quickstart example usage to the module docstring, so that people can do `?BestieTemplate` to get a quick reminder of how to use it.
> Add quickstart example usage to module docstring

- .github/workflows/ReusableTest.yml
- docs/src/91-developer.md
- src/debug/Data.jl
- test/test-bad-usage-and-errors.jl
- test/test-bestie-specific-api.jl
- test/utils.jl
Test that when you generate a package in the previous main
and then update to the HEAD using only the required data
and defaults, that it is the same as generating the package
in the HEAD.
Warning: the interactions with other changes is not clear yet.
Closes #428
Closes #
> Document deprecation and add test for smooth update

- .github/workflows/ReusableTest.yml
- test/test-bestie-specific-api.jl
The ReusableTest workflow creates a main branch due a specific
test recently introduced. That specific runs the generation on main
and on HEAD.
Both activites make no sense if we are running on the main branch,
This creates a condition on the workflow to only run if the
branch is not main (a condition on PRs would also work, but we
leave the possibility of running tests on others branches with
this approach). Furthermore, this also adds a condition in the tests
such that only on main the tests are run.
Closes #435
> Don't create main branch when on main and don't run some tests on main

- CHANGELOG.md
- copier/community.yml
- copier/essential.yml
- docs/src/10-full-guide.md
- src/debug/Data.jl
- src/guess.jl
- template/CITATION.cff.jinja
- template/Project.toml.jinja
- template/docs/make.jl.jinja
- test/test-bestie-specific-api.jl
Deprecate AuthorName and AuthorEmail in favour of Authors.
Authors is a comma-separated list of string.
There are no restriction on the format of each string, but
we hope that it will follow the NAME <EMAIL> format.
If that is the case, many places use regex to get the
NAME or EMAIL only and replace the old usage.
A side-effect is that emails are optional now.
Close #118, #356
Closes #
> Support multiple authors

- copier/ci.yml
- copier/code-quality.yml
- copier/community.yml
- copier/essential.yml
- copier/strategy.yml
- docs/Project.toml
- docs/src/20-explanation.md
- docs/src/30-questions.md
- docs/src/91-developer.md
Add a new field to the copier questions: description.
This is not picked up by copier, it is only used in the new docs page, 30-questions.
Adds a new documentation page 30-questions. This lists the questions and the new description.
Changes the strategy question to include a link to the questions.
Closes #274
> List questions in the documentation

- .github/workflows/Test.yml
- .github/workflows/TestGeneratedPkg.yml
- copier/ci.yml
In the package, use lts instead of 1.6 for Test.yml and TestGeneratedPkg.yml.
For the template, change the JuliaMinCIVersion description to mention "min".
Originally planned to use "min", but it chooses to use 1.6.0.
Closes #415
> Use min for julia-setup

- .github/workflows/TestGeneratedPkg.yml
- CHANGELOG.md
- template/test/runtests.jl.jinja
Fix bug where TestGeneratedPkg was running with the release
version of the package, which invalidated the idea of the
test in the first place.
Closes #450
> TestGeneratedPkg with the HEAD version of the template

- test/test-bestie-specific-api.jl
The update tests try to compare two versions of the generated
package. Since the release is done form the main branch, this
test can't run properly.
This PR checks if the GitHub CI event is release, and don't
run the test if it is.
Can only be properly tested with a new release.
Related to #454
> Don't run update tests on releases

- .github/workflows/Lint.yml
- .github/workflows/PreCommitUpdate.yml
- .github/workflows/ReusableTest.yml
- .github/workflows/TestGeneratedPkg.yml
- template/.github/workflows/Lint.yml.jinja
- template/.github/workflows/{% if AddCopierCI %}Copier.yml{% endif %}.jinja
- template/.github/workflows/{% if AddPrecommit %}PreCommitUpdate.yml{% endif %}.jinja
Add python-version: 3.11 to workflows.
Closes #448
> Add Python version to workflows in package and template

- src/api.jl
Minor addition to the message displayed 'Next steps' afteer generating using BestieTemplate or applying BestieTemplate to an existing package.
As explained in #463 I copy paste the instructions, but first one needs to exit the Julia REPL and execute the following commands in terminal.
I did not update the **documentation** (i.e. full guide) because I think it would be cumbersome and not necessary as what gets print in the terminal, but I am open to suggestions if you feel that we should update that too.
Same for **CHANGELOG.md**, I feel this is a very small change, but will added if is useful.
Closes #463
> Add first command in Next Steps: exit() to exit Julia REPL

- .github/workflows/Test.yml
- Project.toml
- src/BestieTemplate.jl
- src/api.jl
Mark generate, apply and update as public using the public API.
They were already intended to be public by the definition of "documented and
not prepended by `-`" (as opposed to `_copy`, for instance).
Also use the change to add "pre" to the Test workflow.
Closes #473
> Declare generate, apply and update as public

- .github/workflows/ReusableTest.yml
- CHANGELOG.md
- copier/constants.yml
- docs/src/91-developer.md
- src/debug/Data.jl
- test/test-bestie-specific-api.jl
- **Allow using an ENV variable to skip the update test**. If the commit message has `BESTIE_SKIP_UPDATE_TEST`, then the workflow will create that ENV variable.
- **Update LTS version to 1.10**. This is a breaking change that requires manual intervention. See the CHANGELOG for more information.
- **Release v0.13.0**. Let's put 1.10 out there.
Closes #486
> Update LTS to 1.10

- .github/workflows/ReusableTest.yml
Windows fails in the latest tests due to not being able to run the bash
commands to check whether to skip update tests (introduced in #486).
It was not executed in the `main` branch, so it only showed up when
creating a release.
> Fix Windows failures by fixing shell to bash in workflow

- template/.lychee.toml.jinja
[DocuemnterCitations.jl](https://github.com/JuliaDocs/DocumenterCitations.jl) allows to haver latex references and citations, using the syntax
```julia
[bibtex_id](@cite)
```
which currently would cause the links check to fail (see [this example](https://github.com/lucaferranti/DedekindCutArithmetic.jl/actions/runs/11514528897/job/32053329191?pr=3#step:3:108) ). This PR adds `@cite` to excluded links, similar to `@ref` to bypass this problem.
> ignore `@cite` in link checks

- CHANGELOG.md
- copier/ci.yml
- copier/code-quality.yml
- copier/strategy.yml
- docs/src/10-full-guide.md
- docs/src/20-explanation.md
- docs/src/91-developer.md
- src/api.jl
- src/debug/Data.jl
- src/debug/helper.jl
Rename the "Recommended" approach to "Recommended only".
Add a new "recommended-ask" strategy to use the recommended answers
and additionally ask whether the user wants the non-recommended things.
Closes #490
> Implement a new strategy "Recommended and ask extras"

- CHANGELOG.md
- src/debug/helper.jl
> Fix Issue #513

- CHANGELOG.md
- copier/code-quality.yml
- copier/essential.yml
- src/debug/Data.jl
AuthorName and AuthorEmail were deprecated in 0.10.0.
Indentation was deprecated in 0.12.0.
BESTIE_SKIP_UPDATE_TEST is necessary.
Closes #439
> Remove deprecated AuthorName, AuthorEmail, and Indentation

- CHANGELOG.md
- src/BestieTemplate.jl
- src/api.jl
- src/friendly.jl
- src/utils.jl
The installed BestieTemplate will usually be in the .julia folder, read-only.
This leads to the generated package being read-only as well.
To fix this, we change the permissions of the generated package when :local
is used.
Fixed #532
> Change permissions of project when generating using :local

- .markdownlint.json
- CHANGELOG.md
- template/{% if AddFormatterAndLinterConfigFiles %}.markdownlint.json{% endif %}.jinja
This will allow duplicate headers if they have different parents.
This might be a BREAKING CHANGE if you are relying on this behaviour.
To revert, change `siblings_only` to `false` in `.markdownlint.json`.
You can then manually add `` to
explicitly disable it in some files.
Closes #505
> Change default markdownlint configuration MD024.siblings_only to true
