.pre-commit-config.yaml
CITATION.cff
CITATION.cff.jinja

Adds CITATION.cff file and pre-commit hook to check that it is up-to-date.

Add CITATION.cff

---

copier.yml

Add docs/assets/logo.png to copier exclude list

Add docs/assets/logo.png to copier exclude list

---

test/runtests.jl

Fix testing not being done on main

---

.github/workflows/Test.yml
CHANGELOG.md
template/.github/workflows/Test.yml.jinja

Remove nightly from list in Test.yml

---

CHANGELOG.md
CODE_OF_CONDUCT.md
README.md
copier.yml
template/README.md.jinja
template/{% if AddCodeOfConduct %}CODE_OF_CONDUCT.md{% endif %}.jinja
test/runtests.jl

Add CODE_OF_CONDUCT.md and option AddCodeOfConduct to add it to the template.
✅ Closes: #25

feat: 🎸 Add CODE_OF_CONDUCT to pkg and template

---

.github/ISSUE_TEMPLATE/10-bug-report.yml
.github/ISSUE_TEMPLATE/20-feature-request.yml
.github/ISSUE_TEMPLATE/30-usage.yml
.github/ISSUE_TEMPLATE/99-general.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
template/.github/ISSUE_TEMPLATE/10-bug-report.yml.jinja
template/.github/ISSUE_TEMPLATE/20-feature-request.yml.jinja
template/.github/ISSUE_TEMPLATE/30-usage.yml.jinja
template/.github/ISSUE_TEMPLATE/99-general.yml.jinja
template/.github/ISSUE_TEMPLATE/config.yml.jinja
template/.github/PULL_REQUEST_TEMPLATE.md.jinja

And several ISSUE_TEMPLATE files and a PULL_REQUEST_TEMPLATE to the template and package
✅ Closes: #33

feat: 🎸 Add issue and PR templates to template

---

CHANGELOG.md
template/{% if UseCirrusCI %}.cirrus.yml{% endif %}.jinja

Use freebsd-13-2
✅ Closes: #31

ci(template): 🎡 Update Cirrus CI image_family

---

.github/PULL_REQUEST_TEMPLATE.md
template/.github/PULL_REQUEST_TEMPLATE.md.jinja

Links were wrong as well (as in #76)
Closes #

fix: 🐛 Fix PR template

---

CHANGELOG.md
README.md
copier.yml
docs/Project.toml
docs/make.jl
docs/src/90-contributing.md
docs/src/90-developer.md
docs/src/90-reference.md
template/README.md.jinja
template/docs/make.jl.jinja
template/docs/src/90-contributing.md.jinja
template/docs/src/90-developer.md.jinja
template/docs/src/90-reference.md.jinja

The pages are generated based on the contents of the docs/src folder.
✅ Closes: #32

feat: 🎸 Generate docs pages programatically

---

CHANGELOG.md
Project.toml

Release 0.3.0
There is no related issue.

Release 0.3.0

---

.github/dependabot.yml
CHANGELOG.md
template/.github/dependabot.yml

chore: 🤖 Add dependabot

---

.github/workflows/Copier.yml
.github/workflows/Docs.yml
.github/workflows/Lint.yml
.github/workflows/Test.yml
template/.github/workflows/CompatHelper.yml
template/.github/workflows/Copier.yml.jinja
template/.github/workflows/Docs.yml.jinja
template/.github/workflows/Lint.yml
template/.github/workflows/Test.yml.jinja

chore: 🤖 Update action versions in the template

---

.github/workflows/Test.yml

fix: 🐛 Run Test.yml on main always and if template changes

---

.all-contributorsrc
README.md
docs/src/index.md

chore: 🤖 Add all-contributors to repo

---

CHANGELOG.md
README.md

More reader-friendly structure in README

---

README.md

fix: 🐛 Fix missing triple quotes in README

---

CHANGELOG.md
template/{% if License == 'Apache-2.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'GPL-3.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'MIT' %}LICENSE{% endif %}.jinja

Closes #145
Adds authors name to the license file(s)
I've tested locally the behaviour of the generation of the LICENSE file and it works as expected.

Add author and program name to licences

---

.github/ISSUE_TEMPLATE/10-bug-report.yml
.github/ISSUE_TEMPLATE/20-feature-request.yml
.github/ISSUE_TEMPLATE/30-usage.yml
.github/ISSUE_TEMPLATE/99-general.yml

Fix broken link to contributing.md

---

template/{% if License == 'Apache-2.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'GPL-3.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'MIT' %}LICENSE{% endif %}.jinja

Closes #163 
I think there is no need to update the CHANGELOG for such a small change.

Update Year in LICENSE(s)

---

.github/workflows/CompatHelper.yml
.github/workflows/Copier.yml
.github/workflows/Docs.yml
.github/workflows/Lint.yml
.github/workflows/Test.yml
CHANGELOG.md
template/.github/workflows/CompatHelper.yml
template/.github/workflows/Copier.yml.jinja
template/.github/workflows/Docs.yml.jinja
template/.github/workflows/Lint.yml
template/.github/workflows/Test.yml.jinja

Everywhere use julia-actions/cache after setup-julia action + cache pip + cache pre-commit.
Fixes #53

Consistent caching in GitHub workflows

---

docs/src/90-developer.md

docs: ✏️ Add dev docs on how to make a release

---

.gitattributes

chore: 🤖 Add .gitattributes to hide Jinja lang stats

---

README.md

chore: Add copier badge

---

.github/workflows/PreCommitUpdate.yml
template/.github/workflows/PreCommitUpdate.yml

Add a workflow that runs pre-commit autoupdate and create a PR with the
result. Both the package and the template will be updated.
✅ Closes: #91

chore: 🤖 Add a workflow to update pre-commit config

---

.github/workflows/Test.yml

chore: 🤖 Run the Test workflow when copier.yml changes

---

.github/workflows/PreCommitUpdate.yml
template/.github/workflows/PreCommitUpdate.yml

The command pre-commit autoupdate returns 1 whenever there is a change.
We are going to ignore that.

chore: 🤖 Fix PreCommitUpdate workflow

---

.github/workflows/PreCommitUpdate.yml
template/.github/workflows/PreCommitUpdate.yml

This time, we more explicitly ignore the exit code.

fix: 🐛 Fix PreCommitUpdate workflow

---

template/{% if AddAllcontributors %}.all-contributorsrc{% endif %}.jinja

fix: 🐛 Fix template/.all-contributorsrc missing quotes

---

docs/src/90-contributing.md
docs/src/90-developer.md
template/docs/src/90-contributing.md.jinja
template/docs/src/90-developer.md.jinja

Reestructure and add additional information.
Add release information to template.
✅ Closes: #93
Closes #143

docs: ✏️ Update contributing and dev docs in pkg and template

---

README.md
docs/src/10-full-guide.md
docs/src/index.md

docs: ✏️ Update docs explaining copy to existing package

---

copier.yml

fix: 🐛 Fix path in message_after_copy

---

.github/ISSUE_TEMPLATE/10-bug-report.yml
.github/ISSUE_TEMPLATE/20-feature-request.yml
.github/ISSUE_TEMPLATE/30-usage.yml
.github/ISSUE_TEMPLATE/99-general.yml
.github/ISSUE_TEMPLATE/config.yml
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}.jinja/10-bug-report.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}.jinja/20-feature-request.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}.jinja/30-usage.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}.jinja/99-general.yml.jinja

refactor: 💡 Change checklist on issues templates to information

---

copier.yml

docs: ✏️ Improve questions help field

---

docs/src/10-full-guide.md
docs/src/20-explanation.md

Add some docs on the minimum vs recommended option

---

copier.yml
template/.gitignore
template/README.md.jinja
template/docs/make.jl.jinja

- **Add node_modules to .gitignore**
- **Fix template/docs/make.jl formatting**
- **Change allcontributors position in template/README**
- **Requires indentation question**

small fixes

---

docs/src/20-explanation.md

Explain why index.md is not numbered in the docs

---

template/src/{{ PackageName }}.jl.jinja
template/test/runtests.jl.jinja

Add a minimal example to the generated package

---

.github/workflows/TestGeneratedPkg.yml

Workflow to test generated minimal package

---

template/{% if UseCirrusCI %}.cirrus.yml{% endif %}.jinja

- only keep FreeBSD and Julia latest
- do not include code coverage
There is no related issue.

Simplify Cirrus config

---

CHANGELOG.md
template/README.md.jinja

Fixed the two typos
Closes #327

Fix typos in README.md template

---

README.md
docs/src/index.md

Adds the basic Julia pkg lines installation to these files.
Closes #297

Add install information on README and docs/src/index

---

docs/src/20-explanation.md

Explain minimum, recommended, and neither in the explanation docs.
Closes #314

Add section explaining recommended vs minimum

---

codecov.yml
docs/src/91-developer.md
docs/src/95-reference.md
src/debug/Data.jl
src/debug/Debug.jl
src/debug/helper.jl
test/runtests.jl

Create dev tools to help debug the package.
In addition to the data added in #386, this adds a few `dbg_*` functions.
This also updates the dev docs and the reference docs to make it easier to find this information.
Closes #376 
Closes #316

Implement debugging tools to help developers

---

test/aux.jl
test/runtests.jl
test/test-bad-usage-and-errors.jl
test/test-bestie-specific-api.jl
test/test-consistency-with-copier-cli.jl

Create aux.jl and move some helper functions there. Also create a module C to hold constants inside aux.jl. Create test-* files and move the test sets to those files.
Closes #340

Refactor test files

---

.github/workflows/TestGeneratedPkg.yml

The docs tests activates the docs folder and devs the pkg folder.
Closes #333

Change the TestGeneratedPkg docs test to resemble actual use

---

CHANGELOG.md
docs/src/10-full-guide.md
src/api.jl
src/debug/Data.jl
src/guess.jl
test/Project.toml
test/runtests.jl
test/test-bestie-specific-api.jl
test/utils.jl

- **Add keyword guess to apply and more tests on guessing**
- **Guess JuliaMinVersion when applying the template**
- **Guess PackageOwner when applying the template**
- **Guess Indentation when applying the template**
Part of #225

Guess more when applying the package

---

.pre-commit-config.yaml
copier.yml
copier/ci.yml
copier/code-quality.yml
copier/community.yml
copier/constants.yml
copier/essential.yml
copier/strategy.yml

Create some reasonably named files to separate the questions.
The pre-commit check-yaml hook complains about non-standard '!include'
directive and multi-documents.
Closes #416

Refactor the questions into folders

---

CHANGELOG.md
copier/community.yml
src/debug/Data.jl
template/{% if AddCodeOfConduct %}CODE_OF_CONDUCT.md{% endif %}.jinja

Decouple the Code of conduct contact from the AuthorEmail.
Closes #426
Closes #

New question: CodeOfConductContact

---

CHANGELOG.md
copier/essential.yml
src/debug/Data.jl
template/{% if License == 'Apache-2.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'GPL-3.0' %}LICENSE{% endif %}.jinja
template/{% if License == 'MIT' %}LICENSE{% endif %}.jinja

Decouple the copyright holders from the AuthorsName.
Closes #427
Closes #

New question: LicenseCopyrightHolders

---

docs/make.jl
template/docs/make.jl.jinja

Use a variable to improve readibility of docs/make.jl

---

template/README.md.jinja

Add a badge to the template to show support to Bestie.
Closes #296

Add Bestie badge to template

---

docs/src/10-full-guide.md

Small revision in the docs clarifying conflicts and overwriting.
Closes #302, #306

Slight update to the docs application and update

---

template/.github/workflows/Docs.yml.jinja

There is no related issue. This is a minor improvement. Therefore, no need to update CHANGELOG.md

Add name to the steps of documentation CI

---

.github/workflows/TestGeneratedPkg.yml
docs/src/10-full-guide.md
src/api.jl
template/.github/PULL_REQUEST_TEMPLATE.md.jinja
template/.github/workflows/Lint.yml.jinja
template/.github/workflows/Test.yml.jinja
template/.github/workflows/{% if AddCopierCI %}Copier.yml{% endif %}.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/10-bug-report.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/20-feature-request.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/30-usage.yml.jinja
template/.github/{% if AddGitHubTemplates %}ISSUE_TEMPLATE{% endif %}/99-general.yml.jinja
template/CITATION.cff.jinja
template/README.md.jinja
template/docs/make.jl.jinja
template/docs/src/index.md.jinja
template/docs/src/{% if AddContributionDocs %}90-contributing.md{% endif %}.jinja
template/docs/src/{% if AddContributionDocs %}91-developer.md{% endif %}.jinja
template/test/runtests.jl.jinja
test/utils.jl

With a lot of fine tuning, fix the trailing whitespaces,
empty lines, and line endings resulting from the Jinja
variables.
Closes #445

Fix Jinja whitespaces and make pre-commit pass for recommended

---

template/docs/src/{% if AddContributionDocs %}91-developer.md{% endif %}.jinja

fix RP -> PR typo in developer guide
Closes #

fix typo in developer guide

---

.github/workflows/PreCommitUpdate.yml

Propagate pre-commit autoupdate workflow changes to the template

---

src/api.jl

fix: correct wording in api.jl documentation

---

copier/code-quality.yml

Fix print issue in doc https://juliabesties.github.io/BestieTemplate.jl/stable/30-questions/.
There is no related issue.

Avoid backslash in description

---

CHANGELOG.md
Project.toml

Release v0.16.0

---

CHANGELOG.md
Project.toml
src/api.jl

- **Fix missing '_commit' key for :local packages**
- **Only change permissions if dst_path != "."**
- **Release v0.16.2**
Closes #534

Fix missing '_commit' bug and release v0.16.2

---

.copier-answers.yml
README.md

Run `pkg> BestieTemplate.update()`, unstage unwanted changes and commit.
There is no related issue.

Update to BestieTemplate v0.16.2
